name: Build and Deploy

#
# The publishing workflow works as follows:
# - drafts is created in a branch (usually `dev` or `draft_*`)
# - publishing simply means doing a PR to main
# - when the PR is merged, this workflow must be executed first to deploy the content
# - other workflows (like notifications) can be executed after a successful deployment
#

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Generate the website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - name: Build and publish the site
        run: |
          pip install -r requirements.txt
          source ~/.bashrc
          git config --global user.name "hugsy"
          git config --global user.email "hugsy@users.noreply.github.com"
          git clone https://github.com/hugsy/attila.git /tmp/themes/attila
          pelican-themes --install /tmp/themes/attila
          pelican content -o output -s pelicanconf.py
          ghp-import output --no-jekyll --branch=gh-pages --message="Generated new content"
          git push --force origin gh-pages
