name: Build and Deploy

#
# The publishing workflow works as follows:
# - drafts is created in a branch (usually `dev`)
# - publishing simply means doing a PR to main
# - when the PR is merged, this workflow must be executed first to deploy the content
# - other workflows (like notifications) can be executed after a successful deployment
#

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - name: Build the site
        run: |
          pip install -r requirements.txt
          source ~/.bashrc
          git config --local user.name "hugsy"
          git clone --branch master --single-branch https://github.com/hugsy/attila.git themes/attila
          pelican-themes --install themes/attila
          pelican content -o output -s pelicanconf.py
          ghp-import output -b gh-pages
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          branch: gh-pages
          force: true
