name: Check URLs are valid

on:
  # check every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # or on every pull request to main
  pull_request:
    branches:
      - main

jobs:
  link-check:
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.4.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        # Check all markdown in '/content'
        args: --exclude-mail --no-progress 'content/**/*.md'
        # Fail action on broken links
        fail: true
