name: Document Validation

on:
  # on demand or on every pull request/push
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linkcheck:
    name: Link Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Restore lychee cache
        uses: actions/cache@v4.0.2
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.3
        env:
          GITHUB_TOKEN: ${{secrets.LYCHEE_TOKEN}}
        with:
          args: --exclude='^http://rawpixels.net/.*$' --exclude='^http://rawpixels.net/.*$' --exclude='^https://twitter.com/.*$' --exclude='^https://ctftime.org/.*$' --cache --max-cache-age 1w --exclude-all-private --threads 10 --timeout 30 --retry-wait-time 60 --user-agent 'Mozilla/5.0 (Windows NT x.y; rv:10.0) Gecko/20100101 Firefox/10.0' --no-progress 'content/**/*.md'
          fail: true

      - name: Check anchors (setup)
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - name: Check anchors (setup)
        run: |
          zola check


  spellcheck:
    name: Spell Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          task_name: Markdown
          config_path: .github/spellcheck.yml
          output_file: spellcheck-output.txt

      - if: '!cancelled()'
        run: |
          if [ -f spellcheck-output.txt ]; then
              python .github/scripts/ci_spellcheck_format.py spellcheck-output.txt >> ${GITHUB_STEP_SUMMARY}
          fi
