name: Publish Release

on:
  # for notifications, disregard everything that's not in `main` branch
  push:
    branches:
      - main

  # execute the workflow only if build and deploy was successful
  workflow_run:
    workflows:
      - "Build and Deploy"
    types:
      - completed

jobs:
  release_post:
    name: Release a new blog post
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      if: github.event_name == 'push' && contains( join(github.event.commits.*.message), 'New blog post')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: post
