name: Send Notifications

on:
  #
  # Execute the workflow only if build and deploy was successful
  # By dependency, the workflow should only execute on a push to main
  #
  workflow_run:
    workflows:
      - "Publish Release"
    types:
      - completed

jobs:
  twitter_notify:
    name: Send notification on Twitter
    runs-on: ubuntu-latest
    if: contains( join(github.event.commits.*.message), 'New blog post')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - shell: bash
        run: |
          python -m pip install -r scripts/requirements.txt
          python scripts/get_release_info.py
      - uses: ethomson/send-tweet-action@v1
        with:
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          status: ${{ env.BLOG_POST_TWITTER_NOTIFICATION_BODY}}

  # TODO: discord notify
