name: Send Notifications

on:
  # for notifications, disregard everything that's not in `main` branch
  push:
    branches:
      - main

  # execute the workflow only if build and deploy was successful
  workflow_run:
    workflows:
      - "Publish Release"
    types:
      - completed

jobs:
  twitter_notify:
    name: Send notification on Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        if: github.event_name == 'push' && contains( join(github.event.commits.*.message), 'New blog post')
        with:
          status: ${{ join(github.event.commits.*.message) }}... Check it out on https://blahcat.github.io!
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

  # todo: discord