name: Documents Validation

on:
  # check every week on sunday at midnight
  # schedule:
  #   - cron: '0 0 * * 0'
  # or on every pull request to main
  pull_request:
    branches:
      - main

jobs:
  link_check:
    name: Link Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Check links
        uses: lycheeverse/lychee-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          # Check all markdown in '/content'
          args: --exclude-mail --no-progress 'content/**/*.md'
          # Fail action on broken links
          fail: true

